const nodemailer = require('nodemailer');
const express = require('express');
const bodyParser = require('body-parser');
const app = express();
require('dotenv').config();





  



app.use('/src', express.static(`${process.cwd()}/src`));
app.use('/img', express.static(`${process.cwd()}/img`));
app.use('/font', express.static(`${process.cwd()}/font`));
app.use(express.json());
app.use(express.urlencoded({ extended: false }));

var transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
      user: process.env.SENDER,
      pass: process.env.EMAILPASSWORD
    },
    tls: {
      rejectUnauthorized: false
      }
  });
  


app.get('/',  function(req,res){
    res.sendFile(process.cwd()+ '/view/index.html');
});

app.post('/preview',function(req,res){
    var date=[];
    var dollar=[];
    var riel=[];
    var dateReg = /^m[1-3]-w[1-5]-date$/;
    var dollarReg= /^m[1-3]-w[1-5]-date-dollar$/;
    var rielReg= /^m[1-3]-w[1-5]-date-riel$/;

    for (const [key, value] of Object.entries(req.body)) {
        if(dateReg.test(key)){
            if(!value==false){
                date.push(value);
            } else {
                date.push('មិនបានដាក់');
            }
        }
    }

    for (const [key, value] of Object.entries(req.body)) {
        if(dollarReg.test(key)){
            if(!value==false){
                dollar.push(parseFloat(value));
            } else {
                dollar.push(0);
            }
        }
    }

    for (const [key, value] of Object.entries(req.body)) {
        if(rielReg.test(key)){
            if(!value==false){
                riel.push(parseFloat(value));
            } else {
                riel.push(0);
            }
        }
    }

    var trisemester;
    if(req.body.trismemster=='tri-one'){
        trisemester = ['មករា','កុម្ភៈ','មីនា'];
    }else if(req.body.trismemster == 'tri-two'){
        trisemester = ['មេសា','ឧសភា','មិថុនា'];
    }else if(req.body.trismemster=='tri-three'){
        trisemester = ['កក្កដា','សីហា','កញ្ញា'];
    }else if(req.body.trismemster=='tri-four'){
        trisemester = ['តុលា','វិច្ឆិកា','ធ្នូ'];
    }else {
        trisemester = ['','',''];
    }

    var tri;
    if(req.body.trismemster=='tri-one'){
        tri = '១';
    } else if(req.body.trismemster=='tri-two'){
        tri = '២';
    } else if(req.body.trismemster=='tri-three'){
        tri = '៣';
    } else if(req.body.trismemster=='tri-four'){
        tri = '៤';
    } else {
        tri = '';
    }
    console.log(req.body);

    var thisYear = new Date().getFullYear();

    var html = `<google-sheets-html-origin><table xmlns="http://www.w3.org/1999/xhtml" cellspacing="0" cellpadding="0" dir="ltr" border="1" data-sheets-root="1" style="table-layout: fixed; font-size: 10pt; font-family: Arial; width: 0px; border-collapse: collapse; border: none;">
    <thead>
      <tr style="color: rgb(0, 0, 0); font-size: 13.3333px; height: 30px;">
        <th></th>
      </tr>
    </thead><colgroup><col width="46"><col width="266"><col width="110"><col width="112"><col width="147"><col width="159"><col width="120"></colgroup>
    <tbody>
      <tr style="color: rgb(0, 0, 0); font-size: 13.3333px; height: 30px;">
        <td rowspan="1" colspan="7" data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;គ្រីស្ទ​បរិស័ទ​ដំណឹងល្អ​ខ្មែរ​នៃ​និកាយ​ (C&amp;MA) ភូមិភាគ​និរតី ឈ្មោះក្រុមជំនុំ &quot;}" data-sheets-textstyleruns="{&quot;1&quot;:0}{&quot;1&quot;:40,&quot;2&quot;:{&quot;3&quot;:&quot;Arial&quot;}}{&quot;1&quot;:46}" style="border: 1px solid rgb(204, 204, 204); overflow: hidden; padding: 2px 3px; vertical-align: bottom; font-family: Bokor; font-size: 11pt; text-align: center;"><span style="font-size: 11pt; font-family: Bokor, Arial;">គ្រីស្ទ​បរិស័ទ​ដំណឹងល្អ​ខ្មែរ​នៃ​និកាយ​ </span><span style="font-size: 11pt; font-family: Arial;">(C&amp;MA)</span><span style="font-size: 11pt; font-family: Bokor, Arial;"> ភូមិភាគ​និរតី ឈ្មោះក្រុមជំនុំ${req.body.name}</span></td>
      </tr>
      <tr style="color: rgb(0, 0, 0); font-size: 13.3333px; height: 32px;">
        <td rowspan="1" colspan="7" data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;បញ្ជីដង្វាយ ២០% ប្រចាំខែ កក្កដា ឆ្នាំ ${thisYear}&quot;}" data-sheets-textstyleruns="{&quot;1&quot;:0}{&quot;1&quot;:25,&quot;2&quot;:{&quot;5&quot;:1}}{&quot;1&quot;:31}" style="border-width: 1px 1px 3px; border-style: solid; border-color: rgb(204, 204, 204) rgb(204, 204, 204) rgb(0, 0, 0); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: middle; font-family: Battambang; font-size: 11pt; text-align: center;"><span style="font-size: 11pt; font-family: Battambang, Arial;">បញ្ជីដង្វាយ ២០% ប្រចាំខែ </span><span style="font-size: 11pt; font-family: Battambang, Arial; font-weight: bold;">${trisemester[0]}</span><span style="font-size: 11pt; font-family: Battambang, Arial;"> ឆ្នាំ ${thisYear}</span></td>
      </tr>
      <tr style="color: rgb(0, 0, 0); font-size: 13.3333px; height: 21px;">
        <td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;ល.រ&quot;}" style="border-width: 1px 1px 1px 3px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; background-color: rgb(255, 242, 204); font-family: Siemreap; font-weight: bold; text-align: center;">ល.រ</td>
        <td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;កាលបរិច្ឆេទ&quot;}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; background-color: rgb(255, 242, 204); font-family: Siemreap; font-weight: bold; text-align: center;">កាលបរិច្ឆេទ</td>
        <td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;ដង្វាយប្រាក់ដុល្លារ&quot;}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; background-color: rgb(255, 242, 204); font-family: Siemreap; font-weight: bold; text-align: center;">ដង្វាយប្រាក់ដុល្លារ</td>
        <td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;ដង្វាយប្រាក់​រៀល&quot;}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; background-color: rgb(255, 242, 204); font-family: Siemreap; font-weight: bold; text-align: center;">ដង្វាយប្រាក់​រៀល</td>
        <td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;២០% ប្រាក់​ដុល្លារ&quot;}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; background-color: rgb(255, 242, 204); font-family: Siemreap; font-weight: bold; text-align: center;">២០% ប្រាក់​ដុល្លារ</td>
        <td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;២០% ប្រាក់​រៀល&quot;}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; background-color: rgb(255, 242, 204); font-family: Siemreap; font-weight: bold; text-align: center;">២០% ប្រាក់​រៀល</td>
        <td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;ផ្សេងៗ&quot;}" style="border-width: 1px 3px 1px 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; background-color: rgb(255, 242, 204); font-family: Siemreap; font-weight: bold; text-align: center;">ផ្សេងៗ</td>
      </tr>
      <tr style="color: rgb(0, 0, 0); font-size: 13.3333px; height: 21px;">
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:1}" style="border-width: 1px 1px 1px 3px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; font-family: Khmer; text-align: center;">1</td>
        <td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;A&quot;}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: middle; font-size: 11pt; text-align: right;">${date[0]}</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:1}" data-sheets-numberformat="{&quot;1&quot;:2,&quot;2&quot;:&quot;_(\&quot;$\&quot;* #,##0.00_);_(\&quot;$\&quot;* \\(#,##0.00\\);_(\&quot;$\&quot;* \&quot;-\&quot;??_);_(@_)&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; background-color: rgb(255, 255, 255); font-family: Verdana; font-size: 11pt; text-align: right;">$ ${dollar[0]}</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:7}" data-sheets-numberformat="{&quot;1&quot;:2,&quot;2&quot;:&quot;_-* #,##0[$៛-453]_-;\\-* #,##0[$៛-453]_-;_-* \&quot;-\&quot;[$៛-453]_-;_-@&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; background-color: rgb(255, 255, 255); font-family: Verdana; font-size: 11pt; text-align: right;">${riel[0]}៛</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:13}" data-sheets-numberformat="{&quot;1&quot;:2,&quot;2&quot;:&quot;_(\&quot;$\&quot;* #,##0.00_);_(\&quot;$\&quot;* \\(#,##0.00\\);_(\&quot;$\&quot;* \&quot;-\&quot;??_);_(@_)&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; text-align: center;">$ ${dollar[0]*0.2}</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:19}" data-sheets-numberformat="{&quot;1&quot;:4,&quot;2&quot;:&quot;#,##0[$៛]&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; text-align: right;">${riel[0]*0.2}៛</td>
        <td style="border-width: 1px 3px 1px 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom;"></td>
      </tr>
      <tr style="color: rgb(0, 0, 0); font-size: 13.3333px; height: 21px;">
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:2}" style="border-width: 1px 1px 1px 3px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; font-family: Khmer; text-align: center;">2</td>
        <td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;B&quot;}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; text-align: right;">${date[1]}</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:2}" data-sheets-numberformat="{&quot;1&quot;:2,&quot;2&quot;:&quot;_(\&quot;$\&quot;* #,##0.00_);_(\&quot;$\&quot;* \\(#,##0.00\\);_(\&quot;$\&quot;* \&quot;-\&quot;??_);_(@_)&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; background-color: rgb(255, 255, 255); text-align: right;">$ ${dollar[1]}</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:8}" data-sheets-numberformat="{&quot;1&quot;:2,&quot;2&quot;:&quot;_-* #,##0[$៛-453]_-;\\-* #,##0[$៛-453]_-;_-* \&quot;-\&quot;[$៛-453]_-;_-@&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; background-color: rgb(255, 255, 255); text-align: right;">${riel[1]}៛</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:14}" data-sheets-numberformat="{&quot;1&quot;:2,&quot;2&quot;:&quot;_(\&quot;$\&quot;* #,##0.00_);_(\&quot;$\&quot;* \\(#,##0.00\\);_(\&quot;$\&quot;* \&quot;-\&quot;??_);_(@_)&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; text-align: center;">$ ${dollar[1]*0.2}</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:20}" data-sheets-numberformat="{&quot;1&quot;:4,&quot;2&quot;:&quot;#,##0[$៛]&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; text-align: right;">${riel[1]*0.2}៛</td>
        <td style="border-width: 1px 3px 1px 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom;"></td>
      </tr>
      <tr style="color: rgb(0, 0, 0); font-size: 13.3333px; height: 21px;">
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:3}" style="border-width: 1px 1px 1px 3px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; font-family: Khmer; text-align: center;">3</td>
        <td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;C&quot;}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: middle; font-size: 11pt; text-align: right;">${date[2]}</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:3}" data-sheets-numberformat="{&quot;1&quot;:2,&quot;2&quot;:&quot;_(\&quot;$\&quot;* #,##0.00_);_(\&quot;$\&quot;* \\(#,##0.00\\);_(\&quot;$\&quot;* \&quot;-\&quot;??_);_(@_)&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; background-color: rgb(255, 255, 255); font-family: Verdana; font-size: 11pt; text-align: right;">$ ${dollar[2]}</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:9}" data-sheets-numberformat="{&quot;1&quot;:2,&quot;2&quot;:&quot;_-* #,##0[$៛-453]_-;\\-* #,##0[$៛-453]_-;_-* \&quot;-\&quot;[$៛-453]_-;_-@&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; background-color: rgb(255, 255, 255); font-family: Verdana; font-size: 11pt; text-align: right;">${riel[2]}៛</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:15}" data-sheets-numberformat="{&quot;1&quot;:2,&quot;2&quot;:&quot;_(\&quot;$\&quot;* #,##0.00_);_(\&quot;$\&quot;* \\(#,##0.00\\);_(\&quot;$\&quot;* \&quot;-\&quot;??_);_(@_)&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; text-align: center;">$ ${dollar[2]*0.2}</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:21}" data-sheets-numberformat="{&quot;1&quot;:4,&quot;2&quot;:&quot;#,##0[$៛]&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; text-align: right;">${riel[2]*0.2}៛</td>
        <td style="border-width: 1px 3px 1px 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom;"></td>
      </tr>
      <tr style="color: rgb(0, 0, 0); font-size: 13.3333px; height: 21px;">
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:4}" style="border-width: 1px 1px 1px 3px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; font-family: Khmer; text-align: center;">4</td>
        <td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;D&quot;}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: middle; font-size: 11pt; text-align: right;">${date[3]}</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:4}" data-sheets-numberformat="{&quot;1&quot;:2,&quot;2&quot;:&quot;_(\&quot;$\&quot;* #,##0.00_);_(\&quot;$\&quot;* \\(#,##0.00\\);_(\&quot;$\&quot;* \&quot;-\&quot;??_);_(@_)&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; background-color: rgb(255, 255, 255); font-family: Verdana; font-size: 11pt; text-align: right;">$ ${dollar[3]}</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:10}" data-sheets-numberformat="{&quot;1&quot;:2,&quot;2&quot;:&quot;_-* #,##0[$៛-453]_-;\\-* #,##0[$៛-453]_-;_-* \&quot;-\&quot;[$៛-453]_-;_-@&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; background-color: rgb(255, 255, 255); font-family: Verdana; font-size: 11pt; text-align: right;">${riel[3]}៛</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:16}" data-sheets-numberformat="{&quot;1&quot;:2,&quot;2&quot;:&quot;_(\&quot;$\&quot;* #,##0.00_);_(\&quot;$\&quot;* \\(#,##0.00\\);_(\&quot;$\&quot;* \&quot;-\&quot;??_);_(@_)&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; text-align: center;">$ ${dollar[3]*0.2}</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:22}" data-sheets-numberformat="{&quot;1&quot;:4,&quot;2&quot;:&quot;#,##0[$៛]&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; text-align: right;">${riel[3]*0.2}៛</td>
        <td style="border-width: 1px 3px 1px 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom;"></td>
      </tr>
      <tr style="color: rgb(0, 0, 0); font-size: 13.3333px; height: 21px;">
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:5}" style="border-width: 1px 1px 1px 3px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; font-family: Khmer; text-align: center;">5</td>
        <td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;E&quot;}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: middle; font-size: 11pt; text-align: right;">${date[4]}</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:5}" data-sheets-numberformat="{&quot;1&quot;:2,&quot;2&quot;:&quot;_(\&quot;$\&quot;* #,##0.00_);_(\&quot;$\&quot;* \\(#,##0.00\\);_(\&quot;$\&quot;* \&quot;-\&quot;??_);_(@_)&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; background-color: rgb(255, 255, 255); font-family: Verdana; font-size: 11pt; text-align: right;">$ ${dollar[4]}</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:11}" data-sheets-numberformat="{&quot;1&quot;:2,&quot;2&quot;:&quot;_-* #,##0[$៛-453]_-;\\-* #,##0[$៛-453]_-;_-* \&quot;-\&quot;[$៛-453]_-;_-@&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; background-color: rgb(255, 255, 255); font-family: Verdana; font-size: 11pt; text-align: right;">${riel[4]}៛</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:17}" data-sheets-numberformat="{&quot;1&quot;:2,&quot;2&quot;:&quot;_(\&quot;$\&quot;* #,##0.00_);_(\&quot;$\&quot;* \\(#,##0.00\\);_(\&quot;$\&quot;* \&quot;-\&quot;??_);_(@_)&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; text-align: center;">$ ${dollar[4]*0.2}</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:23}" data-sheets-numberformat="{&quot;1&quot;:4,&quot;2&quot;:&quot;#,##0[$៛]&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; text-align: right;">${riel[4]*0.2}៛</td>
        <td style="border-width: 1px 3px 1px 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom;"></td>
      </tr>
      <tr style="color: rgb(0, 0, 0); font-size: 13.3333px; height: 21px;">
        <td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;*&quot;}" style="border-width: 1px 1px 1px 3px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; font-family: Khmer; text-align: center;">*</td>
        <td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;សរុប​ដង្វាយ ២០%&quot;}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; font-family: Moul; text-align: center;">សរុប​ដង្វាយ ២០%</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:6}" data-sheets-numberformat="{&quot;1&quot;:2,&quot;2&quot;:&quot;_(\&quot;$\&quot;* #,##0.00_);_(\&quot;$\&quot;* \\(#,##0.00\\);_(\&quot;$\&quot;* \&quot;-\&quot;??_);_(@_)&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; font-weight: bold; text-align: right;"></td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:12}" data-sheets-numberformat="{&quot;1&quot;:2,&quot;2&quot;:&quot;_-* #,##0[$៛-453]_-;\\-* #,##0[$៛-453]_-;_-* \&quot;-\&quot;[$៛-453]_-;_-@&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; font-weight: bold; text-align: right;"></td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:18}" data-sheets-numberformat="{&quot;1&quot;:2,&quot;2&quot;:&quot;_(\&quot;$\&quot;* #,##0.00_);_(\&quot;$\&quot;* \\(#,##0.00\\);_(\&quot;$\&quot;* \&quot;-\&quot;??_);_(@_)&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; font-weight: bold; text-align: center;">$ ${(dollar[0]+dollar[1]+dollar[2]+dollar[3]+dollar[4])*0.2}</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:24}" data-sheets-numberformat="{&quot;1&quot;:4,&quot;2&quot;:&quot;#,##0[$៛]&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; font-weight: bold; text-align: right;">${(riel[0]+riel[1]+riel[2]+riel[3]+riel[4])*0.2}៛</td>
        <td style="border-width: 1px 3px 1px 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom;"></td>
      </tr>
      <tr style="color: rgb(0, 0, 0); font-size: 13.3333px; height: 28px;">
        <td rowspan="1" colspan="7" data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;បញ្ជីដង្វាយ ២០% ប្រចាំខែ សីហា ឆ្នាំ ២០២៣&quot;}" data-sheets-textstyleruns="{&quot;1&quot;:0}{&quot;1&quot;:25,&quot;2&quot;:{&quot;5&quot;:1}}{&quot;1&quot;:29}" style="border-width: 1px 3px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: middle; font-family: Battambang; font-size: 11pt; text-align: center;"><span style="font-size: 11pt; font-family: Battambang, Arial;">បញ្ជីដង្វាយ ២០% ប្រចាំខែ </span><span style="font-size: 11pt; font-family: Battambang, Arial; font-weight: bold;">${trisemester[1]}</span><span style="font-size: 11pt; font-family: Battambang, Arial;"> ឆ្នាំ ${thisYear}</span></td>
      </tr>
      <tr style="color: rgb(0, 0, 0); font-size: 13.3333px; height: 21px;">
        <td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;ល.រ&quot;}" style="border-width: 1px 1px 1px 3px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; background-color: rgb(255, 242, 204); font-family: Siemreap; font-weight: bold; text-align: center;">ល.រ</td>
        <td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;កាលបរិច្ឆេទ&quot;}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; background-color: rgb(255, 242, 204); font-family: Siemreap; font-weight: bold; text-align: center;">កាលបរិច្ឆេទ</td>
        <td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;ដង្វាយប្រាក់ដុល្លារ&quot;}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; background-color: rgb(255, 242, 204); font-family: Siemreap; font-weight: bold; text-align: center;">ដង្វាយប្រាក់ដុល្លារ</td>
        <td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;ដង្វាយប្រាក់​រៀល&quot;}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; background-color: rgb(255, 242, 204); font-family: Siemreap; font-weight: bold; text-align: center;">ដង្វាយប្រាក់​រៀល</td>
        <td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;២០% ប្រាក់​ដុល្លារ&quot;}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; background-color: rgb(255, 242, 204); font-family: Siemreap; font-weight: bold; text-align: center;">២០% ប្រាក់​ដុល្លារ</td>
        <td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;២០% ប្រាក់​រៀល&quot;}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; background-color: rgb(255, 242, 204); font-family: Siemreap; font-weight: bold; text-align: center;">២០% ប្រាក់​រៀល</td>
        <td style="border-width: 1px 3px 1px 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; background-color: rgb(255, 242, 204);"></td>
      </tr>
      <tr style="color: rgb(0, 0, 0); font-size: 13.3333px; height: 21px;">
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:1}" style="border-width: 1px 1px 1px 3px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; font-family: Khmer; text-align: center;">1</td>
        <td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;F&quot;}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; font-family: Verdana; font-size: 11pt; text-align: right;">${date[5]}</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:25}" data-sheets-numberformat="{&quot;1&quot;:2,&quot;2&quot;:&quot;_(\&quot;$\&quot;* #,##0.00_);_(\&quot;$\&quot;* \\(#,##0.00\\);_(\&quot;$\&quot;* \&quot;-\&quot;??_);_(@_)&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; background-color: rgb(255, 255, 255); font-family: Verdana; font-size: 11pt; text-align: right;">$ ${dollar[5]}</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:31}" data-sheets-numberformat="{&quot;1&quot;:2,&quot;2&quot;:&quot;_-* #,##0[$៛-453]_-;\\-* #,##0[$៛-453]_-;_-* \&quot;-\&quot;[$៛-453]_-;_-@&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; background-color: rgb(255, 255, 255); font-family: Verdana; font-size: 11pt; text-align: right;">${riel[5]}៛</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:37}" data-sheets-numberformat="{&quot;1&quot;:2,&quot;2&quot;:&quot;_(\&quot;$\&quot;* #,##0.00_);_(\&quot;$\&quot;* \\(#,##0.00\\);_(\&quot;$\&quot;* \&quot;-\&quot;??_);_(@_)&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; text-align: center;">$ ${dollar[5]*0.2}</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:43}" data-sheets-numberformat="{&quot;1&quot;:4,&quot;2&quot;:&quot;#,##0[$៛]&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; text-align: right;">${riel[5]*0.2}៛</td>
        <td style="border-width: 1px 3px 1px 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom;"></td>
      </tr>
      <tr style="color: rgb(0, 0, 0); font-size: 13.3333px; height: 21px;">
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:2}" style="border-width: 1px 1px 1px 3px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; font-family: Khmer; text-align: center;">2</td>
        <td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;G&quot;}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; font-family: Verdana; font-size: 11pt; text-align: right;">${date[6]}</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:26}" data-sheets-numberformat="{&quot;1&quot;:2,&quot;2&quot;:&quot;_(\&quot;$\&quot;* #,##0.00_);_(\&quot;$\&quot;* \\(#,##0.00\\);_(\&quot;$\&quot;* \&quot;-\&quot;??_);_(@_)&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; background-color: rgb(255, 255, 255); font-family: Verdana; font-size: 11pt; text-align: right;">$ ${dollar[6]}</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:32}" data-sheets-numberformat="{&quot;1&quot;:2,&quot;2&quot;:&quot;_-* #,##0[$៛-453]_-;\\-* #,##0[$៛-453]_-;_-* \&quot;-\&quot;[$៛-453]_-;_-@&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; background-color: rgb(255, 255, 255); font-family: Verdana; font-size: 11pt; text-align: right;">${riel[6]}៛</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:38}" data-sheets-numberformat="{&quot;1&quot;:2,&quot;2&quot;:&quot;_(\&quot;$\&quot;* #,##0.00_);_(\&quot;$\&quot;* \\(#,##0.00\\);_(\&quot;$\&quot;* \&quot;-\&quot;??_);_(@_)&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; text-align: center;">$ ${dollar[6]*0.2}</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:44}" data-sheets-numberformat="{&quot;1&quot;:4,&quot;2&quot;:&quot;#,##0[$៛]&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; text-align: right;">${riel[6]*0.2}៛</td>
        <td style="border-width: 1px 3px 1px 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom;"></td>
      </tr>
      <tr style="color: rgb(0, 0, 0); font-size: 13.3333px; height: 21px;">
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:3}" style="border-width: 1px 1px 1px 3px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; font-family: Khmer; text-align: center;">3</td>
        <td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;H&quot;}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; text-align: right;">${date[7]}</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:27}" data-sheets-numberformat="{&quot;1&quot;:2,&quot;2&quot;:&quot;_(\&quot;$\&quot;* #,##0.00_);_(\&quot;$\&quot;* \\(#,##0.00\\);_(\&quot;$\&quot;* \&quot;-\&quot;??_);_(@_)&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; background-color: rgb(255, 255, 255); font-family: Verdana; font-size: 11pt; text-align: right;">$ ${dollar[7]}</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:33}" data-sheets-numberformat="{&quot;1&quot;:2,&quot;2&quot;:&quot;_-* #,##0[$៛-453]_-;\\-* #,##0[$៛-453]_-;_-* \&quot;-\&quot;[$៛-453]_-;_-@&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; background-color: rgb(255, 255, 255); font-family: Verdana; font-size: 11pt; text-align: right;">${riel[7]}៛</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:39}" data-sheets-numberformat="{&quot;1&quot;:2,&quot;2&quot;:&quot;_(\&quot;$\&quot;* #,##0.00_);_(\&quot;$\&quot;* \\(#,##0.00\\);_(\&quot;$\&quot;* \&quot;-\&quot;??_);_(@_)&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; text-align: center;">$ ${dollar[7]*0.2}</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:45}" data-sheets-numberformat="{&quot;1&quot;:4,&quot;2&quot;:&quot;#,##0[$៛]&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; text-align: right;">${riel[7]*0.2}៛</td>
        <td style="border-width: 1px 3px 1px 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom;"></td>
      </tr>
      <tr style="color: rgb(0, 0, 0); font-size: 13.3333px; height: 21px;">
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:4}" style="border-width: 1px 1px 1px 3px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; font-family: Khmer; text-align: center;">4</td>
        <td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;I&quot;}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; text-align: right;">${date[8]}</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:28}" data-sheets-numberformat="{&quot;1&quot;:2,&quot;2&quot;:&quot;_(\&quot;$\&quot;* #,##0.00_);_(\&quot;$\&quot;* \\(#,##0.00\\);_(\&quot;$\&quot;* \&quot;-\&quot;??_);_(@_)&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; background-color: rgb(255, 255, 255); font-family: Verdana; font-size: 11pt; text-align: right;">$ ${dollar[8]}</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:34}" data-sheets-numberformat="{&quot;1&quot;:2,&quot;2&quot;:&quot;_-* #,##0[$៛-453]_-;\\-* #,##0[$៛-453]_-;_-* \&quot;-\&quot;[$៛-453]_-;_-@&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; background-color: rgb(255, 255, 255); font-family: Verdana; font-size: 11pt; text-align: right;">${riel[8]}៛</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:40}" data-sheets-numberformat="{&quot;1&quot;:2,&quot;2&quot;:&quot;_(\&quot;$\&quot;* #,##0.00_);_(\&quot;$\&quot;* \\(#,##0.00\\);_(\&quot;$\&quot;* \&quot;-\&quot;??_);_(@_)&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; text-align: center;">$ ${dollar[8]*0.2}</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:46}" data-sheets-numberformat="{&quot;1&quot;:4,&quot;2&quot;:&quot;#,##0[$៛]&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; text-align: right;">${riel[8]*0.2}៛</td>
        <td style="border-width: 1px 3px 1px 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom;"></td>
      </tr>
      <tr style="color: rgb(0, 0, 0); font-size: 13.3333px; height: 21px;">
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:5}" style="border-width: 1px 1px 1px 3px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; font-family: Khmer; text-align: center;">5</td>
        <td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;J&quot;}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; text-align: right;">${date[9]}</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:29}" data-sheets-numberformat="{&quot;1&quot;:2,&quot;2&quot;:&quot;_(\&quot;$\&quot;* #,##0.00_);_(\&quot;$\&quot;* \\(#,##0.00\\);_(\&quot;$\&quot;* \&quot;-\&quot;??_);_(@_)&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; background-color: rgb(255, 255, 255); font-family: Verdana; font-size: 11pt; text-align: right;">$ ${dollar[9]}</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:35}" data-sheets-numberformat="{&quot;1&quot;:2,&quot;2&quot;:&quot;_-* #,##0[$៛-453]_-;\\-* #,##0[$៛-453]_-;_-* \&quot;-\&quot;[$៛-453]_-;_-@&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; background-color: rgb(255, 255, 255); font-family: Verdana; font-size: 11pt; text-align: right;">${riel[9]}៛</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:41}" data-sheets-numberformat="{&quot;1&quot;:2,&quot;2&quot;:&quot;_(\&quot;$\&quot;* #,##0.00_);_(\&quot;$\&quot;* \\(#,##0.00\\);_(\&quot;$\&quot;* \&quot;-\&quot;??_);_(@_)&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; text-align: center;">$ ${dollar[9]*0.2}</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:47}" data-sheets-numberformat="{&quot;1&quot;:4,&quot;2&quot;:&quot;#,##0[$៛]&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; text-align: right;">${riel[9]*0.2}៛</td>
        <td style="border-width: 1px 3px 1px 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom;"></td>
      </tr>
      <tr style="color: rgb(0, 0, 0); font-size: 13.3333px; height: 21px;">
        <td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;*&quot;}" style="border-width: 1px 1px 1px 3px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; font-family: Khmer; text-align: center;">*</td>
        <td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;សរុប​ដង្វាយ ២០%&quot;}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; font-family: Moul; text-align: center;">សរុប​ដង្វាយ ២០%</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:30}" data-sheets-numberformat="{&quot;1&quot;:2,&quot;2&quot;:&quot;_(\&quot;$\&quot;* #,##0.00_);_(\&quot;$\&quot;* \\(#,##0.00\\);_(\&quot;$\&quot;* \&quot;-\&quot;??_);_(@_)&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; background-color: rgb(255, 255, 255); font-family: Verdana; font-size: 11pt; text-align: right;"></td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:36}" data-sheets-numberformat="{&quot;1&quot;:2,&quot;2&quot;:&quot;_-* #,##0[$៛-453]_-;\\-* #,##0[$៛-453]_-;_-* \&quot;-\&quot;[$៛-453]_-;_-@&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; background-color: rgb(255, 255, 255); font-family: Verdana; font-size: 11pt; text-align: right;"></td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:42}" data-sheets-numberformat="{&quot;1&quot;:2,&quot;2&quot;:&quot;_(\&quot;$\&quot;* #,##0.00_);_(\&quot;$\&quot;* \\(#,##0.00\\);_(\&quot;$\&quot;* \&quot;-\&quot;??_);_(@_)&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; text-align: center;">$ ${(dollar[5]+dollar[6]+dollar[7]+dollar[8]+dollar[9])*0.2}</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:48}" data-sheets-numberformat="{&quot;1&quot;:4,&quot;2&quot;:&quot;#,##0[$៛]&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; text-align: right;">${(riel[5]+riel[6]+riel[7]+riel[8]+riel[9])*0.2}៛</td>
        <td style="border-width: 1px 3px 1px 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom;"></td>
      </tr>
      <tr style="color: rgb(0, 0, 0); font-size: 13.3333px; height: 28px;">
        <td rowspan="1" colspan="7" data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;បញ្ជីដង្វាយ ២០% ប្រចាំខែ កញ្ញា ឆ្នាំ ២០២៣&quot;}" data-sheets-textstyleruns="{&quot;1&quot;:0}{&quot;1&quot;:25,&quot;2&quot;:{&quot;5&quot;:1}}{&quot;1&quot;:30}" style="border-width: 1px 3px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: middle; font-family: Battambang; font-size: 11pt; text-align: center;"><span style="font-size: 11pt; font-family: Battambang, Arial;">បញ្ជីដង្វាយ ២០% ប្រចាំខែ </span><span style="font-size: 11pt; font-family: Battambang, Arial; font-weight: bold;">${trisemester[2]}</span><span style="font-size: 11pt; font-family: Battambang, Arial;"> ឆ្នាំ ${thisYear}</span></td>
      </tr>
      <tr style="color: rgb(0, 0, 0); font-size: 13.3333px; height: 21px;">
        <td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;ល.រ&quot;}" style="border-width: 1px 1px 1px 3px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; background-color: rgb(255, 242, 204); font-family: Siemreap; font-weight: bold; text-align: center;">ល.រ</td>
        <td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;កាលបរិច្ឆេទ&quot;}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; background-color: rgb(255, 242, 204); font-family: Siemreap; font-weight: bold; text-align: center;">កាលបរិច្ឆេទ</td>
        <td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;ដង្វាយប្រាក់ដុល្លារ&quot;}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; background-color: rgb(255, 242, 204); font-family: Siemreap; font-weight: bold; text-align: center;">ដង្វាយប្រាក់ដុល្លារ</td>
        <td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;ដង្វាយប្រាក់​រៀល&quot;}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; background-color: rgb(255, 242, 204); font-family: Siemreap; font-weight: bold; text-align: center;">ដង្វាយប្រាក់​រៀល</td>
        <td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;២០% ប្រាក់​ដុល្លារ&quot;}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; background-color: rgb(255, 242, 204); font-family: Siemreap; font-weight: bold; text-align: center;">២០% ប្រាក់​ដុល្លារ</td>
        <td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;២០% ប្រាក់​រៀល&quot;}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; background-color: rgb(255, 242, 204); font-family: Siemreap; font-weight: bold; text-align: center;">២០% ប្រាក់​រៀល</td>
        <td style="border-width: 1px 3px 1px 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; background-color: rgb(255, 242, 204);"></td>
      </tr>
      <tr style="color: rgb(0, 0, 0); font-size: 13.3333px; height: 21px;">
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:1}" style="border-width: 1px 1px 1px 3px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; font-family: Khmer; text-align: center;">1</td>
        <td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;K&quot;}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: middle; font-size: 11pt; text-align: right;">${date[10]}</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:49}" data-sheets-numberformat="{&quot;1&quot;:2,&quot;2&quot;:&quot;_(\&quot;$\&quot;* #,##0.00_);_(\&quot;$\&quot;* \\(#,##0.00\\);_(\&quot;$\&quot;* \&quot;-\&quot;??_);_(@_)&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; background-color: rgb(255, 255, 255); font-family: Verdana; font-size: 11pt; text-align: right;">$ ${dollar[10]}</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:56}" data-sheets-numberformat="{&quot;1&quot;:2,&quot;2&quot;:&quot;_-* #,##0[$៛-453]_-;\\-* #,##0[$៛-453]_-;_-* \&quot;-\&quot;[$៛-453]_-;_-@&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; background-color: rgb(255, 255, 255); font-family: Verdana; font-size: 11pt; text-align: right;">${riel[10]}៛</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:63}" data-sheets-numberformat="{&quot;1&quot;:2,&quot;2&quot;:&quot;_(\&quot;$\&quot;* #,##0.00_);_(\&quot;$\&quot;* \\(#,##0.00\\);_(\&quot;$\&quot;* \&quot;-\&quot;??_);_(@_)&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; text-align: center;">$ ${dollar[10]*0.2}</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:70}" data-sheets-numberformat="{&quot;1&quot;:4,&quot;2&quot;:&quot;#,##0[$៛]&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; text-align: right;">${riel[10]*0.2}៛</td>
        <td style="border-width: 1px 3px 1px 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom;"></td>
      </tr>
      <tr style="color: rgb(0, 0, 0); font-size: 13.3333px; height: 21px;">
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:2}" style="border-width: 1px 1px 1px 3px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; font-family: Khmer; text-align: center;">2</td>
        <td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;L&quot;}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; text-align: right;">${date[11]}</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:50}" data-sheets-numberformat="{&quot;1&quot;:2,&quot;2&quot;:&quot;_(\&quot;$\&quot;* #,##0.00_);_(\&quot;$\&quot;* \\(#,##0.00\\);_(\&quot;$\&quot;* \&quot;-\&quot;??_);_(@_)&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; text-align: right;">$ ${dollar[11]}</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:57}" data-sheets-numberformat="{&quot;1&quot;:2,&quot;2&quot;:&quot;_-* #,##0[$៛-453]_-;\\-* #,##0[$៛-453]_-;_-* \&quot;-\&quot;[$៛-453]_-;_-@&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; text-align: right;">${riel[11]}៛</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:64}" data-sheets-numberformat="{&quot;1&quot;:2,&quot;2&quot;:&quot;_(\&quot;$\&quot;* #,##0.00_);_(\&quot;$\&quot;* \\(#,##0.00\\);_(\&quot;$\&quot;* \&quot;-\&quot;??_);_(@_)&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; text-align: center;">$ ${dollar[11]*0.2}</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:71}" data-sheets-numberformat="{&quot;1&quot;:4,&quot;2&quot;:&quot;#,##0[$៛]&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; text-align: right;">${riel[11]*0.2}៛</td>
        <td style="border-width: 1px 3px 1px 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom;"></td>
      </tr>
      <tr style="color: rgb(0, 0, 0); font-size: 13.3333px; height: 21px;">
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:3}" style="border-width: 1px 1px 1px 3px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; font-family: Khmer; text-align: center;">3</td>
        <td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;M&quot;}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; text-align: right;">${date[12]}</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:51}" data-sheets-numberformat="{&quot;1&quot;:2,&quot;2&quot;:&quot;_(\&quot;$\&quot;* #,##0.00_);_(\&quot;$\&quot;* \\(#,##0.00\\);_(\&quot;$\&quot;* \&quot;-\&quot;??_);_(@_)&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; background-color: rgb(255, 255, 255); font-family: Verdana; font-size: 11pt; text-align: right;">$ ${dollar[12]}</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:58}" data-sheets-numberformat="{&quot;1&quot;:2,&quot;2&quot;:&quot;_-* #,##0[$៛-453]_-;\\-* #,##0[$៛-453]_-;_-* \&quot;-\&quot;[$៛-453]_-;_-@&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; background-color: rgb(255, 255, 255); font-family: Verdana; font-size: 11pt; text-align: right;">${riel[12]}៛</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:65}" data-sheets-numberformat="{&quot;1&quot;:2,&quot;2&quot;:&quot;_(\&quot;$\&quot;* #,##0.00_);_(\&quot;$\&quot;* \\(#,##0.00\\);_(\&quot;$\&quot;* \&quot;-\&quot;??_);_(@_)&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; text-align: center;">$ ${dollar[12]*0.2}</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:72}" data-sheets-numberformat="{&quot;1&quot;:4,&quot;2&quot;:&quot;#,##0[$៛]&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; text-align: right;">${riel[12]*0.2}៛</td>
        <td style="border-width: 1px 3px 1px 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom;"></td>
      </tr>
      <tr style="color: rgb(0, 0, 0); font-size: 13.3333px; height: 21px;">
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:4}" style="border-width: 1px 1px 1px 3px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; font-family: Khmer; text-align: center;">4</td>
        <td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;N&quot;}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; text-align: right;">${date[13]}</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:52}" data-sheets-numberformat="{&quot;1&quot;:2,&quot;2&quot;:&quot;_(\&quot;$\&quot;* #,##0.00_);_(\&quot;$\&quot;* \\(#,##0.00\\);_(\&quot;$\&quot;* \&quot;-\&quot;??_);_(@_)&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; text-align: right;">$ ${dollar[13]}</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:59}" data-sheets-numberformat="{&quot;1&quot;:2,&quot;2&quot;:&quot;_-* #,##0[$៛-453]_-;\\-* #,##0[$៛-453]_-;_-* \&quot;-\&quot;[$៛-453]_-;_-@&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; text-align: right;">${riel[13]}៛</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:66}" data-sheets-numberformat="{&quot;1&quot;:2,&quot;2&quot;:&quot;_(\&quot;$\&quot;* #,##0.00_);_(\&quot;$\&quot;* \\(#,##0.00\\);_(\&quot;$\&quot;* \&quot;-\&quot;??_);_(@_)&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; text-align: center;">$ ${dollar[13]*0.2}</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:73}" data-sheets-numberformat="{&quot;1&quot;:4,&quot;2&quot;:&quot;#,##0[$៛]&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; text-align: right;">${riel[13]*0.2}៛</td>
        <td style="border-width: 1px 3px 1px 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom;"></td>
      </tr>
      <tr style="color: rgb(0, 0, 0); font-size: 13.3333px; height: 21px;">
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:5}" style="border-width: 1px 1px 1px 3px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; font-family: Khmer; text-align: center;">5</td>
        <td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;O&quot;}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; text-align: right;">${date[14]}</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:53}" data-sheets-numberformat="{&quot;1&quot;:2,&quot;2&quot;:&quot;_(\&quot;$\&quot;* #,##0.00_);_(\&quot;$\&quot;* \\(#,##0.00\\);_(\&quot;$\&quot;* \&quot;-\&quot;??_);_(@_)&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; background-color: rgb(255, 255, 255); font-family: Verdana; font-size: 11pt; text-align: right;">$ ${dollar[14]}</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:60}" data-sheets-numberformat="{&quot;1&quot;:2,&quot;2&quot;:&quot;_-* #,##0[$៛-453]_-;\\-* #,##0[$៛-453]_-;_-* \&quot;-\&quot;[$៛-453]_-;_-@&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; background-color: rgb(255, 255, 255); font-family: Verdana; font-size: 11pt; text-align: right;">${riel[14]}៛</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:67}" data-sheets-numberformat="{&quot;1&quot;:2,&quot;2&quot;:&quot;_(\&quot;$\&quot;* #,##0.00_);_(\&quot;$\&quot;* \\(#,##0.00\\);_(\&quot;$\&quot;* \&quot;-\&quot;??_);_(@_)&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; text-align: center;">$ ${dollar[14]*0.2}</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:74}" data-sheets-numberformat="{&quot;1&quot;:4,&quot;2&quot;:&quot;#,##0[$៛]&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; text-align: right;">${riel[14]*0.2}៛</td>
        <td style="border-width: 1px 3px 1px 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom;"></td>
      </tr>
      <tr style="color: rgb(0, 0, 0); font-size: 13.3333px; height: 21px;">
        <td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;*&quot;}" style="border-width: 1px 1px 1px 3px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; font-family: Khmer; text-align: center;">*</td>
        <td data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;សរុប​ដង្វាយ ២០%&quot;}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; font-family: Moul; text-align: center;">សរុប​ដង្វាយ ២០%</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:54}" data-sheets-numberformat="{&quot;1&quot;:2,&quot;2&quot;:&quot;_(\&quot;$\&quot;* #,##0.00_);_(\&quot;$\&quot;* \\(#,##0.00\\);_(\&quot;$\&quot;* \&quot;-\&quot;??_);_(@_)&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; text-align: right;"></td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:61}" data-sheets-numberformat="{&quot;1&quot;:2,&quot;2&quot;:&quot;_-* #,##0[$៛-453]_-;\\-* #,##0[$៛-453]_-;_-* \&quot;-\&quot;[$៛-453]_-;_-@&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; text-align: right;"></td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:68}" data-sheets-numberformat="{&quot;1&quot;:2,&quot;2&quot;:&quot;_(\&quot;$\&quot;* #,##0.00_);_(\&quot;$\&quot;* \\(#,##0.00\\);_(\&quot;$\&quot;* \&quot;-\&quot;??_);_(@_)&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; text-align: center;">$ ${(dollar[10]+dollar[11]+dollar[12]+dollar[13]+dollar[14])*0.2}</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:75}" data-sheets-numberformat="{&quot;1&quot;:4,&quot;2&quot;:&quot;#,##0[$៛]&quot;,&quot;3&quot;:1}" style="border-width: 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; text-align: right;">${(riel[10]+riel[11]+riel[12]+riel[13]+riel[14])*0.2}៛</td>
        <td style="border-width: 1px 3px 1px 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom;"></td>
      </tr>
      <tr style="color: rgb(0, 0, 0); font-size: 13.3333px; height: 47px;">
        <td rowspan="1" colspan="2" data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;សរុប​ដង្វាយ ២០% ត្រីមាសទី ៣/២០២៣&quot;}" style="border-width: 1px 3px 3px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; font-family: Moul; text-align: center;">សរុប​ដង្វាយ ២០% ត្រីមាសទី ${tri} /${thisYear}</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:55}" data-sheets-numberformat="{&quot;1&quot;:2,&quot;2&quot;:&quot;_(\&quot;$\&quot;* #,##0.00_);_(\&quot;$\&quot;* \\(#,##0.00\\);_(\&quot;$\&quot;* \&quot;-\&quot;??_);_(@_)&quot;,&quot;3&quot;:1}" style="border-width: 1px 1px 3px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; font-weight: bold; text-align: center;"></td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:62}" data-sheets-numberformat="{&quot;1&quot;:2,&quot;2&quot;:&quot;_-* #,##0[$៛-453]_-;\\-* #,##0[$៛-453]_-;_-* \&quot;-\&quot;[$៛-453]_-;_-@&quot;,&quot;3&quot;:1}" style="border-width: 1px 1px 3px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; font-weight: bold; text-align: center;"></td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:69}" data-sheets-numberformat="{&quot;1&quot;:2,&quot;2&quot;:&quot;_(\&quot;$\&quot;* #,##0.00_);_(\&quot;$\&quot;* \\(#,##0.00\\);_(\&quot;$\&quot;* \&quot;-\&quot;??_);_(@_)&quot;,&quot;3&quot;:1}" style="border-width: 1px 1px 3px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; background-color: rgb(255, 0, 0); font-size: 14pt; font-weight: bold; text-align: center;">$ ${(dollar[0]+dollar[1]+dollar[2]+dollar[3]+dollar[4]+dollar[5]+dollar[6]+dollar[7]+dollar[8]+dollar[9]+dollar[10]+dollar[11]+dollar[12]+dollar[13]+dollar[14])*0.2}</td>
        <td data-sheets-value="{&quot;1&quot;:3,&quot;3&quot;:76}" data-sheets-numberformat="{&quot;1&quot;:4,&quot;2&quot;:&quot;#,##0[$៛]&quot;,&quot;3&quot;:1}" style="border-width: 1px 1px 3px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom; background-color: rgb(255, 0, 0); font-size: 14pt; font-weight: bold; text-align: right;">${(riel[0]+riel[1]+riel[2]+riel[3]+riel[4]+riel[5]+riel[6]+riel[7]+riel[8]+riel[9]+riel[10]+riel[11]+riel[12]+riel[13]+riel[14])*0.2}៛</td>
        <td style="border-width: 1px 3px 3px 1px; border-style: solid; border-color: rgb(204, 204, 204) rgb(0, 0, 0) rgb(0, 0, 0) rgb(204, 204, 204); border-image: initial; overflow: hidden; padding: 2px 3px; vertical-align: bottom;"></td>
      </tr>
      <tr style="color: rgb(0, 0, 0); font-size: 13.3333px; height: 47px;">
      </tr>
    </tbody>
  </table></google-sheets-html-origin>`;
    var mailOptions = {
        from: process.env.SENDER,
        to: 'sok.sophan@gmail.com',
        subject: 'Sending Email using Node.js',
        html: html
    };
    //end
      
    transporter.sendMail(mailOptions, function(error, info){
        if (error) {
          console.log(error);
        } else {
          console.log('Email sent: ' + info.response);
        }
    });


    res.sendFile(process.cwd()+'/view/preview.html');

});
















// const port = process.env.PORT || 5500;
const port = 5500;
app.listen(port, function() {
    console.log(`Listening on port ${port}`);
});